/**
 * Run Drizzle migrations from ./drizzle (SQL generated by drizzle-kit generate).
 * Use: npm run db:migrate
 *
 * First-time: run npm run db:generate to create migration files from src/db/schema.ts.
 */

import { join } from "node:path";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { getDb } from "./client.js";

async function main(): Promise<void> {
  const migrationsFolder = join(process.cwd(), "drizzle");
  const db = getDb();
  await migrate(db, { migrationsFolder });
  console.log("Migrations applied from", migrationsFolder);
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
